spring:
  application:
    name: spring-serverless-crud-tutorial
  data:
    mongodb:
      uri: mongodb+srv://${host_db}/recipes_db?retryWrites=true&w=majority&appName=${appName}&maxIdleTimeMS=60000&authSource=%24external&authMechanism=MONGODB-AWS
